cat > .github/workflows/ci.yml <<'EOF'
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-shell:
    name: Shell lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run shellcheck on scripts
        run: |
          if ls scripts/*.sh 1> /dev/null 2>&1; then
            shellcheck -x scripts/*.sh || true
          else
            echo "No shell scripts to lint"
          fi

  tests:
    name: Python tests
    runs-on: ubuntu-latest
    needs: lint-shell
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pytest argon2-cffi cryptography keyring
          fi

      - name: Run pytest
        run: |
          pytest -q
EOF
